version: '3.8'

services:
  graphql-apps:
    build:
      context: .
      dockerfile: ./apps/.docker/Dockerfile
    container_name: graphql-apps
    ports:
      - 3015:3015
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    networks:
      - app-network

  graphql-server:
    build: 
      context: .
      dockerfile: ./graphql/.docker/Dockerfile
    container_name: graphql-server
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge